# Generated by Django 5.1.1 on 2024-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='reader_post',
            field=models.ManyToManyField(related_name='my_blogs', to='myblog.readerpost'),
        ),
    ]
